import { Tournament, Player, Team, AuctionPlayer, IncrementRule } from './models';

export const MOCK_PLAYERS: Player[] = [
  {
    id: 1,
    playerNumber: 'P001',
    photoUrl: 'https://i.pravatar.cc/100?img=1&s=100',
    firstName: 'Virat',
    lastName: 'Kohli',
    dob: '1988-11-05',
    role: 'Batsman',
    paymentProofUrl: 'https://picsum.photos/400/300?random=1',
    status: 'APPROVED',
    tournamentId: 1,
  },
  {
    id: 2,
    playerNumber: 'P002',
    photoUrl: 'https://i.pravatar.cc/100?img=2&s=100',
    firstName: 'Rohit',
    lastName: 'Sharma',
    dob: '1987-04-30',
    role: 'Batsman',
    paymentProofUrl: 'https://picsum.photos/400/300?random=2',
    status: 'PENDING',
    tournamentId: 1,
  },
  {
    id: 3,
    playerNumber: 'P003',
    photoUrl: 'https://i.pravatar.cc/100?img=3&s=100',
    firstName: 'Jasprit',
    lastName: 'Bumrah',
    dob: '1993-12-06',
    role: 'Bowler',
    paymentProofUrl: 'https://picsum.photos/400/300?random=3',
    status: 'APPROVED',
    tournamentId: 1,
  },
  {
    id: 4,
    playerNumber: 'P004',
    photoUrl: 'https://i.pravatar.cc/100?img=4&s=100',
    firstName: 'KL',
    dob: '1992-08-18',
    role: 'Batsman',
    paymentProofUrl: 'https://picsum.photos/400/300?random=4',
    status: 'REJECTED',
    tournamentId: 1,
  },
  {
    id: 5,
    playerNumber: 'P005',
    photoUrl: 'https://i.pravatar.cc/100?img=5&s=100',
    firstName: 'Hardik',
    lastName: 'Pandya',
    dob: '1992-10-11',
    role: 'All-rounder',
    paymentProofUrl: 'https://picsum.photos/400/300?random=5',
    status: 'PENDING',
    tournamentId: 1,
  },
  {
    id: 6,
    playerNumber: 'P006',
    photoUrl: 'https://i.pravatar.cc/100?img=6&s=100',
    firstName: 'Yuzvendra',
    lastName: 'Chahal',
    dob: '1990-07-25',
    role: 'Bowler',
    paymentProofUrl: 'https://picsum.photos/400/300?random=6',
    status: 'APPROVED',
    tournamentId: 1,
  },
];

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 1,
    name: 'Cricket Premier League 2026',
    date: '2026-03-20',
    sport: 'Cricket',
    totalTeams: 8,
    totalPlayers: 120,
    status: 'UPCOMING',
    purseAmount: 1000000,
    playersPerTeam: 15,
    basePrice: 20000,
    incrementAmount: 5,
    initialIncrementAmount: 5,
  },
  {
    id: 2,
    name: 'T20 Thunder Cup',
    date: '2026-04-10',
    sport: 'Cricket',
    totalTeams: 6,
    totalPlayers: 90,
    status: 'UPCOMING',
    purseAmount: 750000,
    playersPerTeam: 15,
    basePrice: 15000,
    incrementAmount: 5,
    initialIncrementAmount: 5,
  },
  {
    id: 3,
    name: 'City Cricket Championship',
    date: '2026-02-28',
    sport: 'Cricket',
    totalTeams: 5,
    totalPlayers: 75,
    status: 'ONGOING',
    purseAmount: 500000,
    playersPerTeam: 15,
    basePrice: 10000,
    incrementAmount: 5,
    initialIncrementAmount: 5,
  },
  {
    id: 4,
    name: 'National Cricket League',
    date: '2026-01-15',
    sport: 'Cricket',
    totalTeams: 10,
    totalPlayers: 150,
    status: 'COMPLETED',
    purseAmount: 1200000,
    playersPerTeam: 15,
    basePrice: 25000,
    incrementAmount: 5,
    initialIncrementAmount: 5,
  },
  {
    id: 5,
    name: 'Youth Cricket Series',
    date: '2026-05-01',
    sport: 'Cricket',
    totalTeams: 4,
    totalPlayers: 60,
    status: 'UPCOMING',
    purseAmount: 400000,
    playersPerTeam: 15,
    basePrice: 5000,
    incrementAmount: 5,
    initialIncrementAmount: 5,
  },
];

export const MOCK_INCREMENT_RULES: IncrementRule[] = [
  { id: 1, fromAmount: 0,    toAmount: 500,                incrementBy: 100,  tournamentId: 1 },
  { id: 2, fromAmount: 500,  toAmount: 1000,               incrementBy: 200,  tournamentId: 1 },
  { id: 3, fromAmount: 1000, toAmount: 5000,               incrementBy: 500,  tournamentId: 1 },
  { id: 4, fromAmount: 5000, toAmount: 9223372036854775807, incrementBy: 1000, tournamentId: 1 },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 1,
    teamNumber: 'T001',
    logoUrl: 'https://i.pravatar.cc/150?img=1',
    name: 'Mumbai Tigers',
    ownerName: 'Rajesh Patel',
    mobileNumber: '+91 9876543210',
    tournamentId: 1,
  },
  {
    id: 2,
    teamNumber: 'T002',
    logoUrl: 'https://i.pravatar.cc/150?img=2',
    name: 'Delhi Dynamos',
    ownerName: 'Amit Kumar',
    mobileNumber: '+91 9876543211',
    tournamentId: 1,
  },
  {
    id: 3,
    teamNumber: 'T003',
    logoUrl: 'https://i.pravatar.cc/150?img=3',
    name: 'Bangalore Titans',
    ownerName: 'Priya Singh',
    mobileNumber: '+91 9876543212',
    tournamentId: 1,
  },
  {
    id: 4,
    teamNumber: 'T004',
    logoUrl: 'https://i.pravatar.cc/150?img=4',
    name: 'Kolkata Knights',
    ownerName: 'Vikram Sharma',
    mobileNumber: '+91 9876543213',
    tournamentId: 1,
  },
  {
    id: 5,
    teamNumber: 'T005',
    logoUrl: 'https://i.pravatar.cc/150?img=5',
    name: 'Chennai Champions',
    ownerName: 'Anjali Verma',
    mobileNumber: '+91 9876543214',
    tournamentId: 2,
  },
  {
    id: 6,
    teamNumber: 'T006',
    logoUrl: 'https://i.pravatar.cc/150?img=6',
    name: 'Hyderabad Heroes',
    ownerName: 'Suresh Reddy',
    mobileNumber: '+91 9876543215',
    tournamentId: 2,
  },
];

export const MOCK_AUCTION_PLAYERS: AuctionPlayer[] = [
  {
    id: 1, playerNumber: 'P001',
    photoUrl: 'https://i.pravatar.cc/300?img=11',
    firstName: 'Arjun', lastName: 'Sharma',
    age: 26, city: 'Mumbai',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium',
    role: 'Batsman', basePrice: 20000, auctionStatus: 'SOLD',
    soldToTeamId: 1, soldPrice: 75000, tournamentId: 1,
  },
  {
    id: 2, playerNumber: 'P002',
    photoUrl: 'https://i.pravatar.cc/300?img=12',
    firstName: 'Kiran', lastName: 'Reddy',
    age: 24, city: 'Hyderabad',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Left-Arm Spin',
    role: 'Bowler', basePrice: 20000, auctionStatus: 'SOLD',
    soldToTeamId: 2, soldPrice: 45000, tournamentId: 1,
  },
  {
    id: 3, playerNumber: 'P003',
    photoUrl: 'https://i.pravatar.cc/300?img=13',
    firstName: 'Rahul', lastName: 'Verma',
    age: 29, city: 'Delhi',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin',
    role: 'All-Rounder', basePrice: 20000, auctionStatus: 'SOLD',
    soldToTeamId: 1, soldPrice: 120000, tournamentId: 1,
  },
  {
    id: 4, playerNumber: 'P004',
    photoUrl: 'https://i.pravatar.cc/300?img=14',
    firstName: 'Pradeep', lastName: 'Nair',
    age: 22, city: 'Bangalore',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Left-Arm Fast',
    role: 'Bowler', basePrice: 20000, auctionStatus: 'UNSOLD',
    tournamentId: 1,
  },
  {
    id: 5, playerNumber: 'P005',
    photoUrl: 'https://i.pravatar.cc/300?img=15',
    firstName: 'Vikram', lastName: 'Singh',
    age: 31, city: 'Chennai',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast-Medium',
    role: 'Wicket Keeper', basePrice: 20000, auctionStatus: 'SOLD',
    soldToTeamId: 3, soldPrice: 200000, tournamentId: 1,
  },
  {
    id: 6, playerNumber: 'P006',
    photoUrl: 'https://i.pravatar.cc/300?img=16',
    firstName: 'Aditya', lastName: 'Kulkarni',
    age: 27, city: 'Pune',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Leg Spin',
    role: 'Batsman', basePrice: 20000, auctionStatus: 'SOLD',
    soldToTeamId: 2, soldPrice: 90000, tournamentId: 1,
  },
  {
    id: 7, playerNumber: 'P007',
    photoUrl: 'https://i.pravatar.cc/300?img=17',
    firstName: 'Suresh', lastName: 'Kumar',
    age: 25, city: 'Kolkata',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Medium',
    role: 'All-Rounder', basePrice: 20000, auctionStatus: 'SOLD',
    soldToTeamId: 4, soldPrice: 55000, tournamentId: 1,
  },
  {
    id: 8, playerNumber: 'P008',
    photoUrl: 'https://i.pravatar.cc/300?img=18',
    firstName: 'Naveen', lastName: 'Prasad',
    age: 23, city: 'Lucknow',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast',
    role: 'Bowler', basePrice: 20000, auctionStatus: 'AVAILABLE',
    tournamentId: 1,
  },
  {
    id: 9, playerNumber: 'P009',
    photoUrl: 'https://i.pravatar.cc/300?img=19',
    firstName: 'Deepak', lastName: 'Joshi',
    age: 28, city: 'Ahmedabad',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast',
    role: 'Bowler', basePrice: 20000, auctionStatus: 'AVAILABLE',
    tournamentId: 1,
  },
  {
    id: 10, playerNumber: 'P010',
    photoUrl: 'https://i.pravatar.cc/300?img=20',
    firstName: 'Ravi', lastName: 'Teja',
    age: 30, city: 'Vizag',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Off Spin',
    role: 'Batsman', basePrice: 20000, auctionStatus: 'UNSOLD',
    tournamentId: 1,
  },
  {
    id: 11, playerNumber: 'P011',
    photoUrl: 'https://i.pravatar.cc/300?img=21',
    firstName: 'Manish', lastName: 'Pandey',
    age: 27, city: 'Jaipur',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium',
    role: 'Wicket Keeper', basePrice: 20000, auctionStatus: 'SOLD',
    soldToTeamId: 3, soldPrice: 65000, tournamentId: 1,
  },
  {
    id: 12, playerNumber: 'P012',
    photoUrl: 'https://i.pravatar.cc/300?img=22',
    firstName: 'Sanjay', lastName: 'Mishra',
    age: 24, city: 'Nagpur',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Left-Arm Spin',
    role: 'All-Rounder', basePrice: 20000, auctionStatus: 'AVAILABLE',
    tournamentId: 1,
  },
];


