import { Tournament, Player, Team, AuctionPlayer, IncrementRule } from './models';

export const MOCK_PLAYERS: Player[] = [
  {
    id: '1',
    playerNumber: 'P001',
    photo: 'https://i.pravatar.cc/100?img=1&s=100',
    firstName: 'Virat',
    lastName: 'Kohli',
    dob: '1988-11-05',
    role: 'Batsman',
    paymentProof: 'https://picsum.photos/400/300?random=1',
    status: 'approved',
  },
  {
    id: '2',
    playerNumber: 'P002',
    photo: 'https://i.pravatar.cc/100?img=2&s=100',
    firstName: 'Rohit',
    lastName: 'Sharma',
    dob: '1987-04-30',
    role: 'Batsman',
    paymentProof: 'https://picsum.photos/400/300?random=2',
    status: 'pending',
  },
  {
    id: '3',
    playerNumber: 'P003',
    photo: 'https://i.pravatar.cc/100?img=3&s=100',
    firstName: 'Jasprit',
    lastName: 'Bumrah',
    dob: '1993-12-06',
    role: 'Bowler',
    paymentProof: 'https://picsum.photos/400/300?random=3',
    status: 'approved',
  },
  {
    id: '4',
    playerNumber: 'P004',
    photo: 'https://i.pravatar.cc/100?img=4&s=100',
    firstName: 'KL',
    dob: '1992-08-18',
    role: 'Batsman',
    paymentProof: 'https://picsum.photos/400/300?random=4',
    status: 'rejected',
  },
  {
    id: '5',
    playerNumber: 'P005',
    photo: 'https://i.pravatar.cc/100?img=5&s=100',
    firstName: 'Hardik',
    lastName: 'Pandya',
    dob: '1992-10-11',
    role: 'All-rounder',
    paymentProof: 'https://picsum.photos/400/300?random=5',
    status: 'pending',
  },
  {
    id: '6',
    playerNumber: 'P006',
    photo: 'https://i.pravatar.cc/100?img=6&s=100',
    firstName: 'Yuzvendra',
    lastName: 'Chahal',
    dob: '1990-07-25',
    role: 'Bowler',
    paymentProof: 'https://picsum.photos/400/300?random=6',
    status: 'approved',
  },
];

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: '1',
    name: 'Cricket Premier League 2026',
    date: '2026-03-20',
    sport: 'Cricket',
    totalTeams: 8,
    totalPlayers: 120,
    status: 'upcoming',
    purseAmount: 1000000,
    playersPerTeam: 15,
    basePrice: 20000,
  },
  {
    id: '2',
    name: 'T20 Thunder Cup',
    date: '2026-04-10',
    sport: 'Cricket',
    totalTeams: 6,
    totalPlayers: 90,
    status: 'upcoming',
    purseAmount: 750000,
    playersPerTeam: 15,
    basePrice: 15000,
  },
  {
    id: '3',
    name: 'City Cricket Championship',
    date: '2026-02-28',
    sport: 'Cricket',
    totalTeams: 5,
    totalPlayers: 75,
    status: 'ongoing',
    purseAmount: 500000,
    playersPerTeam: 15,
    basePrice: 10000,
  },
  {
    id: '4',
    name: 'National Cricket League',
    date: '2026-01-15',
    sport: 'Cricket',
    totalTeams: 10,
    totalPlayers: 150,
    status: 'completed',
    purseAmount: 1200000,
    playersPerTeam: 15,
    basePrice: 25000,
  },
  {
    id: '5',
    name: 'Youth Cricket Series',
    date: '2026-05-01',
    sport: 'Cricket',
    totalTeams: 4,
    totalPlayers: 60,
    status: 'upcoming',
    purseAmount: 400000,
    playersPerTeam: 15,
    basePrice: 5000,
  },
];

export const MOCK_INCREMENT_RULES: IncrementRule[] = [
  { id: 'r1', fromAmount: 0,      toAmount: 500,            incrementBy: 100  },
  { id: 'r2', fromAmount: 500,    toAmount: 1000,           incrementBy: 200  },
  { id: 'r3', fromAmount: 1000,   toAmount: 5000,           incrementBy: 500  },
  { id: 'r4', fromAmount: 5000,   toAmount: Number.MAX_SAFE_INTEGER, incrementBy: 1000 },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 't1',
    teamNumber: 'T001',
    logo: 'https://i.pravatar.cc/150?img=1',
    name: 'Mumbai Tigers',
    ownerName: 'Rajesh Patel',
    mobileNumber: '+91 9876543210',
    tournamentId: '1',
  },
  {
    id: 't2',
    teamNumber: 'T002',
    logo: 'https://i.pravatar.cc/150?img=2',
    name: 'Delhi Dynamos',
    ownerName: 'Amit Kumar',
    mobileNumber: '+91 9876543211',
    tournamentId: '1',
  },
  {
    id: 't3',
    teamNumber: 'T003',
    logo: 'https://i.pravatar.cc/150?img=3',
    name: 'Bangalore Titans',
    ownerName: 'Priya Singh',
    mobileNumber: '+91 9876543212',
    tournamentId: '1',
  },
  {
    id: 't4',
    teamNumber: 'T004',
    logo: 'https://i.pravatar.cc/150?img=4',
    name: 'Kolkata Knights',
    ownerName: 'Vikram Sharma',
    mobileNumber: '+91 9876543213',
    tournamentId: '1',
  },
  {
    id: 't5',
    teamNumber: 'T005',
    logo: 'https://i.pravatar.cc/150?img=5',
    name: 'Chennai Champions',
    ownerName: 'Anjali Verma',
    mobileNumber: '+91 9876543214',
    tournamentId: '2',
  },
  {
    id: 't6',
    teamNumber: 'T006',
    logo: 'https://i.pravatar.cc/150?img=6',
    name: 'Hyderabad Heroes',
    ownerName: 'Suresh Reddy',
    mobileNumber: '+91 9876543215',
    tournamentId: '2',
  },
];

export const MOCK_AUCTION_PLAYERS: AuctionPlayer[] = [
  {
    id: 'ap1', playerNumber: 'P001',
    photo: 'https://i.pravatar.cc/300?img=11',
    firstName: 'Arjun', lastName: 'Sharma',
    age: 26, city: 'Mumbai',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium',
    role: 'Batsman', basePrice: 20, auctionStatus: 'upcoming',
  },
  {
    id: 'ap2', playerNumber: 'P002',
    photo: 'https://i.pravatar.cc/300?img=12',
    firstName: 'Kiran', lastName: 'Reddy',
    age: 24, city: 'Hyderabad',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Left-Arm Spin',
    role: 'Bowler', basePrice: 10, auctionStatus: 'upcoming',
  },
  {
    id: 'ap3', playerNumber: 'P003',
    photo: 'https://i.pravatar.cc/300?img=13',
    firstName: 'Rahul', lastName: 'Verma',
    age: 29, city: 'Delhi',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin',
    role: 'All-Rounder', basePrice: 25, auctionStatus: 'upcoming',
  },
  {
    id: 'ap4', playerNumber: 'P004',
    photo: 'https://i.pravatar.cc/300?img=14',
    firstName: 'Pradeep', lastName: 'Nair',
    age: 22, city: 'Bangalore',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Left-Arm Fast',
    role: 'Bowler', basePrice: 15, auctionStatus: 'upcoming',
  },
  {
    id: 'ap5', playerNumber: 'P005',
    photo: 'https://i.pravatar.cc/300?img=15',
    firstName: 'Vikram', lastName: 'Singh',
    age: 31, city: 'Chennai',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast-Medium',
    role: 'Wicket Keeper', basePrice: 30, auctionStatus: 'upcoming',
  },
  {
    id: 'ap6', playerNumber: 'P006',
    photo: 'https://i.pravatar.cc/300?img=16',
    firstName: 'Aditya', lastName: 'Kulkarni',
    age: 27, city: 'Pune',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Leg Spin',
    role: 'Batsman', basePrice: 20, auctionStatus: 'upcoming',
  },
  {
    id: 'ap7', playerNumber: 'P007',
    photo: 'https://i.pravatar.cc/300?img=17',
    firstName: 'Suresh', lastName: 'Kumar',
    age: 25, city: 'Kolkata',
    battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Medium',
    role: 'All-Rounder', basePrice: 15, auctionStatus: 'upcoming',
  },
  {
    id: 'ap8', playerNumber: 'P008',
    photo: 'https://i.pravatar.cc/300?img=18',
    firstName: 'Naveen', lastName: 'Prasad',
    age: 23, city: 'Lucknow',
    battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast',
    role: 'Bowler', basePrice: 10, auctionStatus: 'upcoming',
  },
];
