import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { PlayerService } from '../../core/services/player.service';
import { TournamentService } from '../../core/services/tournament.service';
import { Tournament, Player } from '../../models';
import { AuthImageCachedPipe } from '../../core/pipes/auth-image-cached.pipe';
import { NormalizePhotoUrlCachedPipe } from '../../core/pipes/normalize-photo-url-cached.pipe';

@Component({
  selector: 'app-players',
  imports: [
    CommonModule,
    FormsModule,
    AuthImageCachedPipe,
    NormalizePhotoUrlCachedPipe,
  ],
  templateUrl: './teams.html',
  styleUrls: ['./teams.scss'],
})
export class Players implements OnInit {
  tournament: Tournament | null = null;
  players: Player[] = [];
  selectedImage: string | null = null;
  selectedImageName: string = '';
  selectedPlayerId: number | null = null;
  isLoading = true;
  minLoadingTime = 800;
  loadingStartTime = 0;
  pendingRequests = 0;

  // Add Player Form
  showAddPlayerModal = false;
  newPlayer = {
    firstName: '',
    lastName: '',
    dob: '',
    role: 'BATSMAN',
    photoFile: null as File | null,
    paymentProofFile: null as File | null,
  };
  playerPhotoPreview: string | null = null;

  // Edit Player Form
  showEditPlayerModal = false;
  editingPlayer: Player | null = null;
  editPlayerForm = {
    firstName: '',
    lastName: '',
    dob: '',
    role: 'BATSMAN',
    photoFile: null as File | null,
    paymentProofFile: null as File | null,
  };
  editPhotoPreview: string | null = null;

  private tournamentId!: number;
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private playerService = inject(PlayerService);
  private tournamentService = inject(TournamentService);
  private cdr = inject(ChangeDetectorRef);

  ngOnInit() {
    this.loadingStartTime = Date.now();
    this.pendingRequests = 2; // tournament + players
    
    this.route.paramMap.subscribe((params) => {
      const id = Number(params.get('tournamentId'));
      if (id) {
        this.tournamentId = id;
        this.tournamentService.getById(id).subscribe((t) => {
          this.tournament = t;
          this.completeRequest();
        });
        this.loadPlayers();
      }
    });
  }

  private completeRequest() {
    this.pendingRequests--;
    if (this.pendingRequests <= 0) {
      const elapsedTime = Date.now() - this.loadingStartTime;
      const remainingTime = Math.max(0, this.minLoadingTime - elapsedTime);
      
      if (remainingTime > 0) {
        setTimeout(() => {
          this.isLoading = false;
          this.cdr.markForCheck();
        }, remainingTime);
      } else {
        this.isLoading = false;
        this.cdr.markForCheck();
      }
    }
  }

  private loadPlayers() {
    this.playerService.getByTournament(this.tournamentId).subscribe({
      next: (data) => {
        this.players = data;
        this.completeRequest();
      },
      error: () => {
        alert('Failed to load players.');
        this.completeRequest();
      },
    });
  }

  openAddPlayerModal() {
    this.showAddPlayerModal = true;
    this.resetPlayerForm();
  }

  generateNextPlayerNumber() {
    // Player numbers are now auto-generated by the backend
  }

  closeAddPlayerModal() {
    this.showAddPlayerModal = false;
    this.resetPlayerForm();
  }

  resetPlayerForm() {
    this.newPlayer = {
      firstName: '',
      lastName: '',
      dob: '',
      role: 'BATSMAN',
      photoFile: null,
      paymentProofFile: null,
    };
    this.playerPhotoPreview = null;
  }

  calculateAge(dob: string | undefined): string {
    if (!dob) {
      return 'N/A';
    }
    const today = new Date();
    const birthDate = new Date(dob);
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    return age.toString();
  }

  deletePlayer(playerId: number) {
    if (confirm('Are you sure you want to delete this player?')) {
      this.playerService.delete(playerId).subscribe({
        next: () => {
          this.players = this.players.filter((p) => p.id !== playerId);
          this.cdr.markForCheck();
        },
        error: () => alert('Failed to delete player.'),
      });
    }
  }

  onPlayerPhotoSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.newPlayer.photoFile = file;
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.playerPhotoPreview = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  }

  onPaymentProofSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.newPlayer.paymentProofFile = file;
    }
  }

  addPlayer() {
    if (!this.newPlayer.firstName || !this.newPlayer.role) {
      alert('Please fill in all required fields (First Name, Role)');
      return;
    }

    // Use public registration endpoint (admin adds player directly)
    this.playerService
      .register(this.tournamentId, {
        firstName: this.newPlayer.firstName,
        lastName: this.newPlayer.lastName || undefined,
        dob: this.newPlayer.dob || undefined,
        role: this.newPlayer.role,
        photo: this.newPlayer.photoFile ?? undefined,
        paymentProof: this.newPlayer.paymentProofFile ?? undefined,
      })
      .subscribe({
        next: (p) => {
          this.players.push(p);
          this.closeAddPlayerModal();
          this.cdr.markForCheck();
        },
        error: () => alert('Failed to add player.'),
      });
  }

  openImageModal(imageSrc: string | undefined, playerName: string, playerId?: number) {
    if (!imageSrc) return;
    this.selectedImage = imageSrc;
    this.selectedImageName = playerName;
    this.selectedPlayerId = playerId ?? null;
  }

  closeImageModal() {
    this.selectedImage = null;
    this.selectedImageName = '';
    this.selectedPlayerId = null;
  }

  approvePlayer(playerId: number) {
    this.playerService.approve(playerId).subscribe({
      next: (updated) => {
        const player = this.players.find((p) => p.id === playerId);
        if (player) player.status = updated.status;        this.cdr.markForCheck();      },
      error: () => alert('Failed to approve player.'),
    });
  }

  rejectPlayer(playerId: number) {
    this.playerService.reject(playerId).subscribe({
      next: (updated) => {
        const player = this.players.find((p) => p.id === playerId);
        if (player) player.status = updated.status;        this.cdr.markForCheck();      },
      error: () => alert('Failed to reject player.'),
    });
  }

  approveFromModal() {
    if (this.selectedPlayerId) {
      this.approvePlayer(this.selectedPlayerId);
      this.closeImageModal();
    }
  }

  rejectFromModal() {
    if (this.selectedPlayerId) {
      this.rejectPlayer(this.selectedPlayerId);
      this.closeImageModal();
    }
  }

  openEditPlayerModal(player: Player) {
    this.editingPlayer = player;
    this.editPlayerForm = {
      firstName: player.firstName,
      lastName: player.lastName || '',
      dob: player.dob || '',
      role: player.role,
      photoFile: null,
      paymentProofFile: null,
    };
    this.editPhotoPreview = player.photoUrl ?? null;
    this.showEditPlayerModal = true;
  }

  closeEditPlayerModal() {
    this.showEditPlayerModal = false;
    this.editingPlayer = null;
    this.editPhotoPreview = null;
  }

  onEditPhotoSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.editPhotoPreview = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  }

  onEditPaymentProofSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.editPlayerForm.paymentProofFile = file;
    }
  }

  saveEditPlayer() {
    if (!this.editingPlayer) return;
    if (!this.editPlayerForm.firstName) {
      alert('First Name is required');
      return;
    }
    this.playerService
      .update(this.editingPlayer.id, {
        firstName: this.editPlayerForm.firstName,
        lastName: this.editPlayerForm.lastName || undefined,
        dob: this.editPlayerForm.dob || undefined,
        role: this.editPlayerForm.role,
        photo: this.editPlayerForm.photoFile ?? undefined,
        paymentProof: this.editPlayerForm.paymentProofFile ?? undefined,
      })
      .subscribe({
        next: (updated) => {
          const index = this.players.findIndex((p) => p.id === this.editingPlayer!.id);
          if (index !== -1) this.players[index] = updated;
          this.closeEditPlayerModal();
          this.cdr.markForCheck();
        },
        error: () => alert('Failed to update player.'),
      });
  }

  goBack() {
    this.router.navigate(['/admin']);
  }
}
